import esbuild from 'esbuild';
import process from 'node:process';
import { builtinModules } from 'node:module';

const builtins = [...builtinModules, ...builtinModules.map((name) => `node:${name}`)];

const production = process.argv[2] === 'production';

const banner = `/*
This is a generated/bundled file. Source lives in src/. See the repository.
*/`;

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins,
	],
	format: 'cjs',
	target: 'es2022',
	logLevel: 'info',
	sourcemap: production ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: production,
});

if (production) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
